import "@/app/globals.css";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Learning Next.js ",
    absolute: "",
    template: "%s | Next.js",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="flex justify-center items-center text-5xl m-4">
          Header
        </header>
        {children}
        <footer className="flex justify-center items-center text-5xl m-4">
          Footer
        </footer>
      </body>
    </html>
  );
}
